#!/bin/sh

while true; do
    sinac -w "$((1*60))"      # when inactive for $1 minutes
    if [ $(cat ~/.awakeuntil) -le $(date +%s) ]; then # not a presentation
        xset dpms force off   # blank screen (provoke the user to to sth)
        sleep 5.01            # give the user time
        if [ $(sinac) -ge 5 ]; then
            ~/cogs/turtlemode # if nobody is here, lock that nobody out
        fi
    fi
done
