#!/bin/bash

location="${HOME}/.ramfs"

if [ x"$(mount | grep $location)" == "x" ];
then 
    echo Error: $location not mounted >&2
    exit 1
else
    rsync -av --delete $location $location.save
fi


