#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

setxkbmap -option caps:escape
xbindkeys & # cannot run as service, requires logind session (as with devmon)
systemctl --user start desktop.target &
xmonad
systemctl --user stop desktop.target
