--- 
- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/home/andres/mail/andres.erbsen@gmail.com/all_mail
  usual: true
  archived: false
  id: 1
  labels: []

- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/home/andres/mail/sent
  usual: false
  archived: false
  id: 4
  labels: 
  - sent
- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/home/andres/mail/andres.erbsen@gmail.com/spam
  usual: true
  archived: true
  id: 2
  labels: 
  - spam
- !masanjin.net,2006-10-01/Redwood/Maildir 
  uri: maildir:/home/andres/mail/andres.erbsen@gmail.com/trash
  usual: true
  archived: true
  id: 3
  labels: 
  - deleted
- !masanjin.net,2006-10-01/Redwood/SentLoader {}

